/* confdefs.h */
#define PACKAGE_NAME "ELF_Linker"
#define PACKAGE_TARNAME "elf_linker"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "ELF_Linker 1.0"
#define PACKAGE_BUGREPORT "Guillaume.Huard@imag.fr"
#define PACKAGE_URL ""
#define PACKAGE "elf_linker"
#define VERSION "1.0"
#define YYTEXT_POINTER 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_FCNTL_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_FORK 1
#define HAVE_VFORK 1
#define HAVE_WORKING_VFORK 1
#define HAVE_WORKING_FORK 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define HAVE_STDLIB_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_GETPAGESIZE 1
#define HAVE_MMAP 1
#define HAVE_STDLIB_H 1
#define HAVE_REALLOC 1
#define HAVE_ALARM 1
#define HAVE_BZERO 1
#define HAVE_DUP2 1
#define HAVE_GETHOSTBYADDR 1
#define HAVE_GETHOSTBYNAME 1
#define HAVE_MUNMAP 1
#define HAVE_SELECT 1
#define HAVE_SOCKET 1
#define HAVE_STRERROR 1
